#!/bin/bash

# set -x

/usr/bin/jhbuild -f /srv/jhbuildbot/gtk-buildmaster/jhbuildrc \
        bot \
        --start-server \
        --buildbot-dir=/srv/jhbuildbot/gtk-buildmaster/builddir \
        --slaves-dir=/srv/jhbuildbot/gtk-buildmaster/slaves \
        --daemon $@

